// Code generated by protoc-gen-go. DO NOT EDIT.
// source: call.proto

package call

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CallType int32

const (
	CallType_QUERY_DATABASE       CallType = 0
	CallType_CREATE_DATABASE      CallType = 1
	CallType_UPDATE_DATABASE      CallType = 2
	CallType_DROP_DATABASE        CallType = 3
	CallType_QUERY_TABLE          CallType = 4
	CallType_CREATE_TABLE         CallType = 5
	CallType_ALTER_TABLE          CallType = 6
	CallType_DROP_TABLE           CallType = 7
	CallType_QUERY_ROW            CallType = 8
	CallType_QUERY_PAGINATION_ROW CallType = 9
	CallType_INSERT_ROW           CallType = 10
	CallType_UPDATE_ROW           CallType = 11
	CallType_DELETE_ROW           CallType = 12
)

var CallType_name = map[int32]string{
	0:  "QUERY_DATABASE",
	1:  "CREATE_DATABASE",
	2:  "UPDATE_DATABASE",
	3:  "DROP_DATABASE",
	4:  "QUERY_TABLE",
	5:  "CREATE_TABLE",
	6:  "ALTER_TABLE",
	7:  "DROP_TABLE",
	8:  "QUERY_ROW",
	9:  "QUERY_PAGINATION_ROW",
	10: "INSERT_ROW",
	11: "UPDATE_ROW",
	12: "DELETE_ROW",
}

var CallType_value = map[string]int32{
	"QUERY_DATABASE":       0,
	"CREATE_DATABASE":      1,
	"UPDATE_DATABASE":      2,
	"DROP_DATABASE":        3,
	"QUERY_TABLE":          4,
	"CREATE_TABLE":         5,
	"ALTER_TABLE":          6,
	"DROP_TABLE":           7,
	"QUERY_ROW":            8,
	"QUERY_PAGINATION_ROW": 9,
	"INSERT_ROW":           10,
	"UPDATE_ROW":           11,
	"DELETE_ROW":           12,
}

func (x CallType) String() string {
	return proto.EnumName(CallType_name, int32(x))
}

func (CallType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{0}
}

type CallInfo struct {
	Type                 CallType `protobuf:"varint,1,opt,name=type,proto3,enum=call.CallType" json:"type,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallInfo) Reset()         { *m = CallInfo{} }
func (m *CallInfo) String() string { return proto.CompactTextString(m) }
func (*CallInfo) ProtoMessage()    {}
func (*CallInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{0}
}

func (m *CallInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallInfo.Unmarshal(m, b)
}
func (m *CallInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallInfo.Marshal(b, m, deterministic)
}
func (m *CallInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallInfo.Merge(m, src)
}
func (m *CallInfo) XXX_Size() int {
	return xxx_messageInfo_CallInfo.Size(m)
}
func (m *CallInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CallInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CallInfo proto.InternalMessageInfo

func (m *CallInfo) GetType() CallType {
	if m != nil {
		return m.Type
	}
	return CallType_QUERY_DATABASE
}

func (m *CallInfo) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterEnum("call.CallType", CallType_name, CallType_value)
	proto.RegisterType((*CallInfo)(nil), "call.CallInfo")
}

func init() { proto.RegisterFile("call.proto", fileDescriptor_caa5955d5eab2d2d) }

var fileDescriptor_caa5955d5eab2d2d = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4d, 0x4f, 0x83, 0x40,
	0x10, 0x40, 0xdd, 0x8a, 0xfd, 0x98, 0x52, 0x8a, 0xa3, 0x07, 0x8e, 0x4d, 0x4f, 0x8d, 0x87, 0x1e,
	0xf4, 0x17, 0x6c, 0xcb, 0x44, 0x49, 0x08, 0xe0, 0x74, 0x1b, 0xe3, 0xc9, 0xd4, 0x06, 0x4f, 0x04,
	0x88, 0xe1, 0xd2, 0x7f, 0xee, 0xd1, 0xcc, 0x2e, 0x86, 0x78, 0xdb, 0xf7, 0x66, 0xf6, 0x65, 0xb3,
	0x00, 0xe7, 0x53, 0x55, 0x6d, 0xdb, 0xef, 0xa6, 0x6b, 0xd0, 0x93, 0xf3, 0xfa, 0x05, 0xa6, 0xfb,
	0x53, 0x55, 0x25, 0xf5, 0x57, 0x83, 0x6b, 0xf0, 0xba, 0x4b, 0x5b, 0x46, 0x6a, 0xa5, 0x36, 0xc1,
	0x63, 0xb0, 0xb5, 0xcb, 0x32, 0x35, 0x97, 0xb6, 0x64, 0x3b, 0xc3, 0x08, 0x26, 0xe7, 0xa6, 0xee,
	0xca, 0xba, 0x8b, 0x46, 0x2b, 0xb5, 0xf1, 0xf9, 0x0f, 0x1f, 0x7e, 0x94, 0x4b, 0xc9, 0x32, 0x22,
	0x04, 0xaf, 0x47, 0xe2, 0xf7, 0x8f, 0x58, 0x1b, 0xbd, 0xd3, 0x07, 0x0a, 0xaf, 0xf0, 0x0e, 0x96,
	0x7b, 0x26, 0x6d, 0x68, 0x90, 0x4a, 0xe4, 0xb1, 0x88, 0xff, 0xc9, 0x11, 0xde, 0xc2, 0x22, 0xe6,
	0xbc, 0x18, 0xd4, 0x35, 0x2e, 0x61, 0xee, 0x82, 0x46, 0xef, 0x52, 0x0a, 0x3d, 0x0c, 0xc1, 0xef,
	0x6b, 0xce, 0xdc, 0xc8, 0x8a, 0x4e, 0x0d, 0x71, 0x2f, 0xc6, 0x18, 0x00, 0xd8, 0x8c, 0xe3, 0x09,
	0x2e, 0x60, 0xe6, 0x1a, 0x9c, 0xbf, 0x85, 0x53, 0x8c, 0xe0, 0xde, 0x61, 0xa1, 0x9f, 0x93, 0x4c,
	0x9b, 0x24, 0xcf, 0xec, 0x64, 0x26, 0x17, 0x93, 0xec, 0x40, 0x6c, 0x2c, 0x83, 0x70, 0xff, 0x48,
	0xe1, 0xb9, 0x0d, 0x53, 0x4a, 0x3d, 0xfb, 0x9f, 0x63, 0xfb, 0xa3, 0x4f, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xa0, 0xa4, 0xf4, 0x88, 0x5f, 0x01, 0x00, 0x00,
}
