// Code generated by protoc-gen-go. DO NOT EDIT.
// source: row.proto

package row

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockData_JoinType int32

const (
	//不连接
	BlockData_JOIN_NONE BlockData_JoinType = 0
	//(存在分裂，记录行列表最后一条行部分数据包含在下一个块中)
	//行值连接
	BlockData_JOIN_ROW BlockData_JoinType = 1
	//列值连接
	BlockData_JOIN_COLUMN BlockData_JoinType = 2
)

var BlockData_JoinType_name = map[int32]string{
	0: "JOIN_NONE",
	1: "JOIN_ROW",
	2: "JOIN_COLUMN",
}

var BlockData_JoinType_value = map[string]int32{
	"JOIN_NONE":   0,
	"JOIN_ROW":    1,
	"JOIN_COLUMN": 2,
}

func (x BlockData_JoinType) String() string {
	return proto.EnumName(BlockData_JoinType_name, int32(x))
}

func (BlockData_JoinType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dbfce2cce8f2e8cd, []int{0, 0}
}

type BlockData struct {
	Id                   int32              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TxId                 string             `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Time                 int64              `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Rows                 []*RowData         `protobuf:"bytes,4,rep,name=rows,proto3" json:"rows,omitempty"`
	Join                 BlockData_JoinType `protobuf:"varint,5,opt,name=join,proto3,enum=row.BlockData_JoinType" json:"join,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BlockData) Reset()         { *m = BlockData{} }
func (m *BlockData) String() string { return proto.CompactTextString(m) }
func (*BlockData) ProtoMessage()    {}
func (*BlockData) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbfce2cce8f2e8cd, []int{0}
}

func (m *BlockData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockData.Unmarshal(m, b)
}
func (m *BlockData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockData.Marshal(b, m, deterministic)
}
func (m *BlockData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockData.Merge(m, src)
}
func (m *BlockData) XXX_Size() int {
	return xxx_messageInfo_BlockData.Size(m)
}
func (m *BlockData) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockData.DiscardUnknown(m)
}

var xxx_messageInfo_BlockData proto.InternalMessageInfo

func (m *BlockData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BlockData) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *BlockData) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *BlockData) GetRows() []*RowData {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *BlockData) GetJoin() BlockData_JoinType {
	if m != nil {
		return m.Join
	}
	return BlockData_JOIN_NONE
}

type RowData struct {
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Op                   uint32        `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	Columns              []*ColumnData `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RowData) Reset()         { *m = RowData{} }
func (m *RowData) String() string { return proto.CompactTextString(m) }
func (*RowData) ProtoMessage()    {}
func (*RowData) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbfce2cce8f2e8cd, []int{1}
}

func (m *RowData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowData.Unmarshal(m, b)
}
func (m *RowData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowData.Marshal(b, m, deterministic)
}
func (m *RowData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowData.Merge(m, src)
}
func (m *RowData) XXX_Size() int {
	return xxx_messageInfo_RowData.Size(m)
}
func (m *RowData) XXX_DiscardUnknown() {
	xxx_messageInfo_RowData.DiscardUnknown(m)
}

var xxx_messageInfo_RowData proto.InternalMessageInfo

func (m *RowData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RowData) GetOp() uint32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *RowData) GetColumns() []*ColumnData {
	if m != nil {
		return m.Columns
	}
	return nil
}

type ColumnData struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColumnData) Reset()         { *m = ColumnData{} }
func (m *ColumnData) String() string { return proto.CompactTextString(m) }
func (*ColumnData) ProtoMessage()    {}
func (*ColumnData) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbfce2cce8f2e8cd, []int{2}
}

func (m *ColumnData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnData.Unmarshal(m, b)
}
func (m *ColumnData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnData.Marshal(b, m, deterministic)
}
func (m *ColumnData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnData.Merge(m, src)
}
func (m *ColumnData) XXX_Size() int {
	return xxx_messageInfo_ColumnData.Size(m)
}
func (m *ColumnData) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnData.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnData proto.InternalMessageInfo

func (m *ColumnData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("row.BlockData_JoinType", BlockData_JoinType_name, BlockData_JoinType_value)
	proto.RegisterType((*BlockData)(nil), "row.BlockData")
	proto.RegisterType((*RowData)(nil), "row.RowData")
	proto.RegisterType((*ColumnData)(nil), "row.ColumnData")
}

func init() { proto.RegisterFile("row.proto", fileDescriptor_dbfce2cce8f2e8cd) }

var fileDescriptor_dbfce2cce8f2e8cd = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x50, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x76, 0x4a, 0x9b, 0xeb, 0x5f, 0x74, 0x0c, 0x78, 0xb4, 0x32, 0x05, 0x21, 0x65, 0x28,
	0x0b, 0x33, 0x85, 0xa1, 0x15, 0x24, 0x92, 0x55, 0xc4, 0x58, 0x85, 0xa6, 0x83, 0xa1, 0xcd, 0x45,
	0xa9, 0x51, 0xca, 0x43, 0xf2, 0x4e, 0x28, 0x27, 0x0a, 0x6c, 0x77, 0xdf, 0x9d, 0xbe, 0x3f, 0x08,
	0x1b, 0x6a, 0xd3, 0xba, 0x21, 0x4f, 0xa8, 0x1a, 0x6a, 0xe3, 0x2f, 0x01, 0xe1, 0xdd, 0x8e, 0x36,
	0xef, 0xf7, 0x85, 0x2f, 0x70, 0x02, 0xd2, 0x95, 0x5a, 0x18, 0x91, 0xf4, 0xac, 0x74, 0x25, 0x5e,
	0x40, 0xcf, 0x1f, 0xd7, 0xae, 0xd4, 0xd2, 0x88, 0x24, 0xb4, 0x81, 0x3f, 0x2e, 0x4a, 0x44, 0x08,
	0xbc, 0xdb, 0x6f, 0xb5, 0x32, 0x22, 0x51, 0x96, 0x67, 0x34, 0x10, 0x34, 0xd4, 0x1e, 0x74, 0x60,
	0x54, 0x32, 0x9c, 0x8d, 0xd2, 0x4e, 0xc5, 0x52, 0xdb, 0x91, 0x5a, 0xbe, 0xe0, 0x35, 0x04, 0x6f,
	0xe4, 0x2a, 0xdd, 0x33, 0x22, 0x99, 0xcc, 0x2e, 0xf9, 0xe3, 0x57, 0x38, 0x5d, 0x92, 0xab, 0x56,
	0x9f, 0xf5, 0xd6, 0xf2, 0x53, 0x7c, 0x0b, 0x83, 0x13, 0x82, 0x63, 0x08, 0x97, 0xf9, 0x22, 0x5b,
	0x67, 0x79, 0xf6, 0x10, 0x9d, 0xe1, 0x08, 0x06, 0xbc, 0xda, 0xfc, 0x25, 0x12, 0x38, 0x85, 0x21,
	0x6f, 0xf3, 0xfc, 0xf1, 0xf9, 0x29, 0x8b, 0x64, 0xbc, 0x82, 0xfe, 0x8f, 0xee, 0xbf, 0x30, 0x8a,
	0xc3, 0x4c, 0x40, 0x52, 0xcd, 0x49, 0xc6, 0x56, 0x52, 0x8d, 0x57, 0xd0, 0xdf, 0xd0, 0xee, 0x63,
	0x5f, 0x1d, 0xb4, 0x62, 0xdb, 0x53, 0x36, 0x35, 0x67, 0x8c, 0x9d, 0x9f, 0xee, 0xb1, 0x01, 0xf8,
	0x83, 0xbb, 0x02, 0xca, 0xc2, 0x17, 0x4c, 0x3d, 0xb2, 0x3c, 0xbf, 0x9e, 0x73, 0xa7, 0x37, 0xdf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xb5, 0x13, 0xf6, 0x60, 0x01, 0x00, 0x00,
}
